### ISSUE TITLE
3.0.0-M2 Micrometer binders

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#164]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M2-Release-Notes#micrometer-binders

**Comment by BoykoAlex** [comment]
See https://github.com/openrewrite/rewrite-spring/pull/201

If package rename is all we want then this should do it:
```
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.Micrometer_3_0
displayName: Micrometer compatible with Boot 3.x
description: Switch to Micrometer compatible with Boot 3.x
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: io.micrometer.core.instrument.binder
      newPackageName: io.micrometer.binder
      recursive: true
```
