### ISSUE TITLE
Rework OpenRewrite recipe integration

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#181]
### What needs to be done
OpenRewrite recipes should be runnable from within SBM.
It should also be possible to use OpenRewrite recipes inside SBM recipes

### Why it needs to be done
OpenRewrite has a large set of recipes available which should be available in SBM.
This allows us to contribute recipes to OpenRewrite and still use them in SBM.

#### Reference OpenRewrite recipe by name

**Given**

Java class
````
@java.lang.Deprecated
public class Foo {}
````

SBM YAML recipe (`src/main/resources/recipes/test-recipe.yaml`)
```
- name: test-recipe
  description: Replace deprecated spring.datasource.* properties
  condition:
    type: org.springframework.sbm.common.migration.conditions.TrueCondition
  actions:
    - type: org.springframework.sbm.engine.recipe.OpenRewriteDeclarativeRecipeAdapter
      description: Call a OpenRewrite recipe
      openRewriteRecipe: |-
        type: specs.openrewrite.org/v1beta/recipe
        name: org.openrewrite.java.RemoveAnnotation
        displayName: Order imports
        description: Order imports
        recipeList:
          - org.openrewrite.java.RemoveAnnotation:
              annotationPattern: "@java.lang.Deprecated"
```

**When**

Recipe is applied `apply test-recipe`

**Then** 

The OpenRewrite recipe ` org.openrewrite.java.RemoveAnnotation` as declared in `src/main/resources/recipes/test-recipe.yaml` is applied and the annotation was removed

Java class
````
public class Foo {}
````

#### Reference OpenRewrite recipe by name

**Given**

Java class
````
@java.lang.Deprecated
public class Foo {}
````

SBM YAML recipe (`src/main/resources/recipes/test-recipe.yaml`)
```
- name: test-recipe
  description: "Remove @Deprecated annotations"
  condition:
    type: org.springframework.sbm.common.migration.conditions.TrueCondition
  actions:
    - type: org.springframework.sbm.engine.recipe.OpenRewriteNamedRecipeAdapter
      description: "Call a OpenRewrite recipe to remove @Deprecated annotations"
      openRewriteRecipeName: org.springframework.sbm.dummy.RemoveDeprecatedAnnotation
```

OpenRewrite recipe (`src/main/resources/META-INF/rewrite/test-recipe.yml`)
````
type: specs.openrewrite.org/v1beta/recipe
name: org.springframework.sbm.dummy.RemoveDeprecatedAnnotation
displayName: Order imports
description: Order imports
recipeList:
  - org.openrewrite.java.RemoveAnnotation:
      annotationPattern: "@java.lang.Deprecated"
````

**When** 

Recipe is applied `apply test-recipe`

**Then** 

The OpenRewrite recipe `src/main/resources/META-INF/rewrite/test-recipe.yml` was applied and the `@Deprecated` annotation was removed

Java class
````
public class Foo {}
````
