### ISSUE TITLE
3.0.0-M2 - Configuration Changelog - Removed

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#258]
labels: ["good first issue","upgrade:boot-recipe","3.0.0"]

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M2-Configuration-Changelog#removed-in-300-m2

| Key                                                 | Replacement                                           | Reason | TODO |
|-----------------------------------------------------|-------------------------------------------------|--------|-----:|
| management.metrics.export.ganglia.protocol-version  | No longer used by Micrometer.                         |    | remove |
| spring.banner.image.bitdepth                        | Support for image banners has been removed.           |    | remove |
| spring.banner.image.height                          | Support for image banners has been removed.           |    | remove |
| spring.banner.image.invert                          | Support for image banners has been removed.           |    | remove |
| spring.banner.image.location                        | Support for image banners has been removed.           |    | remove |
| spring.banner.image.margin                          | Support for image banners has been removed.           |     |remove |
| spring.banner.image.pixelmode                       | Support for image banners has been removed.           |     |remove |
| spring.banner.image.width                           | Support for image banners has been removed.           |     |remove |
| spring.data.cassandra.connection.connection-timeout |    |    | remove |
| spring.kafka.listener.only-log-record-metadata      | Use KafkaUtils#setConsumerRecordFormatter instead.    |    |   recipe |
| spring.mongodb.embedded.features                    | Feature support has been removed from Embedded Mongo. |     |remove |
| spring.mustache.allow-request-override              |    |     |remove |
| spring.mustache.allow-session-override              |     |     |remove |
| spring.mustache.cache                               |     |     |remove |
| spring.mustache.content-type                        |     |     | remove |
| spring.mustache.expose-request-attributes           |    |      | remove |
| spring.mustache.expose-session-attributes           |     |     | remove |
| spring.mustache.expose-spring-macro-helpers         |     |     | remove |

### What needs to be done
All occurrences of properties marked as `remove` should just be deleted.
This recipe exists in OpenRewrite and can be 

- [ ] Verify if this recipe exists in [`rewrite-spring`](https://github.com/openrewrite/rewrite-spring) FYI: @pway99?
- [ ] If it exists find its name
- [ ] If it doesn't exist create a new OpenRewrite recipe under `sbm-recipes-boot-upgrade/src/main/resources/META-INF/rewrite/remove-spring-boot3-upgrade-remove-properties.yml` and create a contribution in `rewrite-spring`
````
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.RemovedSpringBootProperties
displayName: Remove old Spring Boot properties
description: Removes all removed properties found in any properties file
recipeList:
  - org.openrewrite.properties.DeleteProperty:
       propertyKey: management.metrics.export.ganglia.protocol-version
  - org.openrewrite.yaml.DeleteProperty:
       propertyKey: management.metrics.export.ganglia.protocol-version
...
````
- [ ] include rewrite recipe (by name) into `boot-2.7-3.0-dependency-version-update.yaml`
- [ ] If the recipe was contributed, create a new issue to replace the local recipe with the OpenRewrite version when released
