### ISSUE TITLE
Add/Look into Dependabot support

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#31]
Would adding a tool like Dependabot or Renovate be an option for this project? That could eliminate the need to explicitly upgrade dependencies by hand.. [Looking through the list](https://docs.openrewrite.org/reference/latest-versions-of-every-openrewrite-module) both of these properties are outdated:
```
  <openrewrite.version>7.16.3</openrewrite.version>
  <openrewrite.spring.version>4.14.1</openrewrite.spring.version>
```

The most recent versions as of writing are:
```
  <openrewrite.version>7.19.0</openrewrite.version>
  <openrewrite.spring.version>4.17.0</openrewrite.spring.version>
```

_Originally posted by @timtebeek in https://github.com/spring-projects-experimental/spring-boot-migrator/issues/7#issuecomment-1072763714_

**Comment by timtebeek** [comment]
Short version is that Dependabot is easiest to get started with, as it's part of GitHub.
You'd need a file `.github/dependabot.yml` with content such as the following:
```yaml
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
```
Adding this file would help surface any new dependency versions daily, along with any compile / test incompatibilities.

Renovate is a separate app & oauth, but still quite easy to add and also supports bumping the maven wrapper for instance.
You're on Maven wrapper version 3.6.3 for instance, and Renovate would also create a wrapper bump to 3.8.5 for you.
