### ISSUE TITLE
3.0 Upgrade Recipe: Spring MVC and WebFlux URL matching changes - add additional paths

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#561]
> **Note**
> **Spring Boot 3 migration recipes should be created using plain OpenRewrite Visitors and Recipes whenever possible as we want to contribute them to OpenRewrite.**
> See [Authoring Recipes](https://docs.openrewrite.org/tutorials/authoring-recipes) and [Declarative YAML Recipes](https://docs.openrewrite.org/reference/yaml-format-reference)
> Also see [rewrite](https://github.com/openrewrite/rewrite), [rewrite-spring](https://github.com/openrewrite/rewrite-spring) and [rewrite-migrate-java](https://github.com/openrewrite/rewrite-migrate-java) repositories to check if existing Visitors and Recipes can be used. 

## What needs to be done

An automated migration recipe for [`Spring MVC and WebFlux URL matching changes`](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M4-Release-Notes#spring-mvc-and-webflux-url-matching-changes) should be created.

**Given**
````java
@GetMapping(path="/some-path")
public String somePath() {
  ...
}

@PostMapping("/another-path")
public String anotherPath() {
  ...
}
````

**Expected**
````java
@GetMapping(path={"/some-path", "/some-path/"})
public String somePath() {
  ...
}

@PostMapping({"/another-path", "/another-path/"})
public String anotherPath() {
  ...
}
````

The migration recipe `sbu30-522-add-additional-paths-to-request-mapping` should be created.
An additional path with trailing `/` should be added to all request mappings (e.g. `@GetMapping`).

### Condition
  Any class `UsesType` of `org.springframework.web.bind.annotation.RestController`

### Report Section Issue

#522 

### DoD
- [ ] Action implemented
  - [ ] Description provided
  - [ ] Tests (single and multi-module)
- [ ] Condition implemented / reused
  - [ ] Description provided
  - [ ] Tests (single and multi-module)
- [ ] Recipe yaml added
  - [ ] Test
  - [ ] Integration test (single and multi-module) 

### Recipe YAML Examples

This section provides examples of how an automated migration recipe can be defined in SBM `YAML` which can then be contributed to OpenRewrite.

#### OpenRewrite already provides a recipe
In this case, the `OpenRewriteNamedRecipeAdapter` should be used to reference the OpenRewrite recipe by name.

<details>
<summary><b>Existing OpenRewrite recipe by name</b></summary>

````yaml
- name: sbu30-migrate-javax-to-jakarta
  description: Spring boot 3.0 Upgrade - Migrate javax packages to new jakarta packages
  condition:
    type: org.springframework.sbm.common.migration.conditions.TrueCondition
  actions:

    - type: org.springframework.sbm.engine.recipe.OpenRewriteNamedRecipeAdapter
      condition:
        type: org.springframework.sbm.boot.common.conditions.IsSpringBootProject
        versionPattern: "3\\.0\\..*"
      description: Replace javax with new jakarta packages
      openRewriteRecipeName: org.openrewrite.java.migrate.JavaxMigrationToJakarta
````

</details>

#### No recipe exists for this migration and the recipe can be declared using YAML
In this case, `OpenRewriteDeclarativeRecipeAdapter` should embed OpenRewrite's declaratíve YAML syntax.

<details>
<summary><b>Migration Recipe with embedded OpenRewrite YAML syntax</b></summary>

````yaml
- name: sbu30-remove-image-banner
  description: Spring boot 3.0 Upgrade - Remove the image banner at src/main/resources
  condition:
    type: org.springframework.sbm.common.migration.conditions.TrueCondition
  actions:
    - type: org.springframework.sbm.engine.recipe.OpenRewriteDeclarativeRecipeAdapter
      condition:
        type: org.springframework.sbm.boot.upgrade_27_30.report.helper.BannerSupportHelper
      description: Remove the image banner at src/main/resources
      openRewriteRecipe: |-
        type: specs.openrewrite.org/v1beta/recipe
        name: org.openrewrite.RemoveSpringBootImageBanner
        displayName: Remove the image banner at `src/main/resources`
        description: Remove the image banner at `src/main/resources`
        recipeList:
          - org.openrewrite.DeleteSourceFiles:
              filePattern: "{**/src,src}/main/resources/banner.{gif,png,jpg}"
````

</details>

## Additional Resources & Information
- Example
- Testing Actions
- Testing Conditions
- Testing Recipes
- Integration Tests
