### ISSUE TITLE
Spike: Parse Release Notes

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#563]
### What needs to be done
The Boot Release Notes can be cloned from the Wiki:
`git clone https://github.com/spring-projects/spring-boot.wiki.git`

- Generate templates to create GH issues from the extracted Release Notes --> `GH-Issue-<Title-from-Release Notes>.yaml`
- Use these files to bulk create GH Issues and store mapping between <Title-from-Release Notes> --> GH Issue ID
- Generate Report recipe `YAML` from the extracted Release Note sections containing the GH-Issue that was previously created

````YAML
       # ===================
        # TODO: generated
        # ===================
        - title: <Title from Release Notes>
          helper: AlwaysTheSameDefaultHelperReturningTrue
          change: |-
            <Test from Release Notes>
          affected: |-
            Actually, we don't know if the applicaiton is really affected. But please think about contributing.
            Have a look into issue #<GH-Issue>
          remediation:
            description: |-
              See affected
          projects: spring-boot
          gitHubIssue: <GH-Issue>
          contributors:
            - Here might be YOUR name!
````
