### ISSUE TITLE
Modify the Spring Boot 3 Upgrade YAML to take `Condition` as alternative to `Helper`

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#591]
### What needs to be done
The `sections` in the Spring Boot 3 Upgrade Report YAML should allow to declare a `Condition` as alternative to the current `Helper`.

With `Helper`
````YAML
        - title: Actuator Endpoints Sanitization
          helper: org.springframework.sbm.boot.upgrade_27_30.report.helper.ActuatorEndpointsSanitizationHelper
          change: |-
````

With `Condition`
````YAML
        - title: Actuator Endpoints Sanitization
          helper:
            type: org.springframework.sbm.boot.upgrade_27_30.report.helper.ConditionOnlyHelper
            condition:
              type: org.springframework.sbm.java.migration.conditions.HasImportStartingWith
              value: "a.b"
          change: |-
````

### Acceptance Criteria

/info panel
**Given** precondition
**When** action
**Then** result
